//sample link http://www.images.connect4education.com/maps/composer/contemporary_composerIndividual.html?cID=36&myURL=@metafile=w file:///cd|/audio/N4003B.mp3 @endmetafile')">Meet Erik Satie</a>

//COMPOSER PROFILES
//sample link http://www.images.connect4education.com/maps/composer/contemporary_composerIndividual.html?cID=36&myURL=@metafile=w file:///cd|/audio/N4003B.mp3 @endmetafile')">Meet Erik Satie</a>

var cProfiles = [
['0','Bach','baroque_composerIndividual.html', 'Johann Sebastian'],
['1','Handel','baroque_composerIndividual.html'],
['2','Monteverdi','baroque_composerIndividual.html'],
['3','Lully','baroque_composerIndividual.html'],
['4','Carissimi','baroque_composerIndividual.html'],
['5','Sch%C3%BCtz','baroque_composerIndividual.html'],
['6','Cavalli','baroque_composerIndividual.html'],
['7','Corelli','baroque_composerIndividual.html'],
['8','Purcell','baroque_composerIndividual.html'],
['9','Telemann','baroque_composerIndividual.html'],
['10','Scarlatti','baroque_composerIndividual.html'],
['11','Vivaldi','baroque_composerIndividual.html'],
['12','Couperin','baroque_composerIndividual.html'],
['13','Rameau','baroque_composerIndividual.html'],
['0','Bellini','romantic_composerIndividual.html'],
['1','Schumann','romantic_composerIndividual.html', 'Robert'],
['2','Wagner','romantic_composerIndividual.html'],
['3','Rossini','romantic_composerIndividual.html'],
['4','Berlioz','romantic_composerIndividual.html'],
['5','Mendelssohn','romantic_composerIndividual.html'],
['6','Czerny','romantic_composerIndividual.html'],
['7','Weber','romantic_composerIndividual.html'],
['8','Schubert','romantic_composerIndividual.html'],
['9','Liszt','romantic_composerIndividual.html'],
['10','Verdi','romantic_composerIndividual.html'],
['11','Schumann','romantic_composerIndividual.html', 'Clara Wieck'],
['12','Brahms','romantic_composerIndividual.html'],
['13','Saint-Sa%C3%ABns','romantic_composerIndividual.html'],
['14','Donizetti','romantic_composerIndividual.html'],
['15','Paganini','romantic_composerIndividual.html'],
['16','Smetana','romantic_composerIndividual.html'],
['17','Strauss Jr.','romantic_composerIndividual.html', 'Johann'],
['18','Elgar','romantic_composerIndividual.html'],
['19','Grieg','romantic_composerIndividual.html'],
['20','Glinka','romantic_composerIndividual.html'],
['21','Rimsky-Korsakov','romantic_composerIndividual.html'],
['22','Dvor%C3%A1k','romantic_composerIndividual.html'],
['23','Tchaikovsky','romantic_composerIndividual.html'],
['24','Fauré','romantic_composerIndividual.html'],
['25','Satie','romantic_composerIndividual.html'],
['26','Puccini','romantic_composerIndividual.html'],
['27','Mahler','romantic_composerIndividual.html'],
['28','Strauss','romantic_composerIndividual.html', 'Richard'],
['29','Rachmaninov','romantic_composerIndividual.html'],
['31','Bruch','romantic_composerIndividual.html'],
['32','Bruckner','romantic_composerIndividual.html'],
['33','Mussorgsky','romantic_composerIndividual.html'],
['34','Chopin','romantic_composerIndividual.html'],
['35','Le Beau','romantic_composerIndividual.html'],
['36','Lang','romantic_composerIndividual.html'],
['37','Beach','romantic_composerIndividual.html'],
['38','Hensel','romantic_composerIndividual.html'],
['0','Bach','classical_composerIndividual.html', 'Carl Philipp Emanuel'],
['1','Bach','classical_composerIndividual.html', 'Johann Christian'],
['2','Gluck','classical_composerIndividual.html'],
['3','Haydn','classical_composerIndividual.html'],
['4','Mozart','classical_composerIndividual.html'],
['5','Beethoven','classical_composerIndividual.html'],
['0','Webern','contemporary_composerIndividual.html'],
['1','Berg','contemporary_composerIndividual.html'],
['2','Bart%C3%B3k','contemporary_composerIndividual.html'],
['3','Williams','contemporary_composerIndividual.html'],
['4','Britten','contemporary_composerIndividual.html'],
['5','Boulanger','contemporary_composerIndividual.html'],
['6','Messiaen','contemporary_composerIndividual.html'],
['7','Boulez','contemporary_composerIndividual.html'],
['8','Stockhausen','contemporary_composerIndividual.html'],
['9','Hindemith','contemporary_composerIndividual.html'],
['10','Orff','contemporary_composerIndividual.html'],
['11','Berio','contemporary_composerIndividual.html'],
['12','Jobim','contemporary_composerIndividual.html'],
['13','Gil','contemporary_composerIndividual.html'],
['14','Villa-Lobos','contemporary_composerIndividual.html'],
['15','Chavez','contemporary_composerIndividual.html'],
['16','Ginastera','contemporary_composerIndividual.html'],
['17','Prokofiev','contemporary_composerIndividual.html'],
['18','Shostakovich','contemporary_composerIndividual.html'],
['19','Piston','contemporary_composerIndividual.html'],
['20','Still','contemporary_composerIndividual.html'],
['21','Copland','contemporary_composerIndividual.html'],
['22','Honegger','contemporary_composerIndividual.html'],
['23','Poulenc','contemporary_composerIndividual.html'],
['24','Catan','contemporary_composerIndividual.html'],
['25','Stravinsky','contemporary_composerIndividual.html'],
['26','Barber','contemporary_composerIndividual.html'],
['27','Cage','contemporary_composerIndividual.html'],
['28','Debussy','contemporary_composerIndividual.html'],
['29','Gershwin','contemporary_composerIndividual.html'],
['30','Glass','contemporary_composerIndividual.html'],
['31','Gorecki','contemporary_composerIndividual.html'],
['32','Holst','contemporary_composerIndividual.html'],
['33','Joplin','contemporary_composerIndividual.html'],
['34','Ravel','contemporary_composerIndividual.html'],
['35','Penderecki','contemporary_composerIndividual.html'],
['36','Satie','contemporary_composerIndividual.html'],
['37','Schoenberg','contemporary_composerIndividual.html'],
['38','Scriabin','contemporary_composerIndividual.html'],
['39','Ellington','contemporary_composerIndividual.html'],
['40','De Falla','contemporary_composerIndividual.html'],
['41','Sibelius','contemporary_composerIndividual.html'],
['0','Desprez','renaissance_composerIndividual.html'],
['1','da Palestrina','renaissance_composerIndividual.html'],
['2','de Victoria','renaissance_composerIndividual.html'],
['3','Farmer','renaissance_composerIndividual.html'],
['4','Janequin','renaissance_composerIndividual.html'],
['5','Dowland','renaissance_composerIndividual.html'],
['6','Weelkes','renaissance_composerIndividual.html'],
['7','Byrd','renaissance_composerIndividual.html'],
['8','Ockeghem','renaissance_composerIndividual.html'],
['9','Obrecht','renaissance_composerIndividual.html'],
['10','Dunstable','renaissance_composerIndividual.html'],
];